//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
using Unity.NetCode.EditorTests.Generated;

namespace Unity.NetCode.EditorTests.Generated
{
    [UpdateInGroup(typeof(ClientAndServerInitializationSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : SystemBase
    {
        protected override void OnCreate()
        {
            var ghostCollectionSystem = World.GetOrCreateSystem<GhostCollectionSystem>();
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGenTestTypeFlatGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostValueSerializerGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostTypeIndexGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsChildLevelComponentGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostPredictedOnlyGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostInterpolatedOnlyGhostComponentSerializer.State);
        }

        protected override void OnUpdate()
        {
            var parentGroup = World.GetExistingSystem<InitializationSystemGroup>();
            if (parentGroup != null)
            {
                parentGroup.RemoveSystemFromUpdateList(this);
            }
        }
    }
}